services:
  local-proxy-gw:
    build: .
    container_name: local-proxy-gw
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    # ВОТ ОНО! Без этого ядро Linux внутри контейнера сбрасывает чужие пакеты
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      - proxynet
    environment:
      - PROXY_TYPE=${PROXY_TYPE}
      - PROXY_IP=${PROXY_IP}
      - PROXY_PORT=${PROXY_PORT}
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASS=${PROXY_PASS}

networks:
  proxynet:
    external: true